# Generated by Django 3.0.14 on 2024-02-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mentor',
        ),
    ]
