# Generated by Django 3.0.14 on 2024-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_image',
            field=models.ImageField(default=1, upload_to='static/Faculty/'),
            preserve_default=False,
        ),
    ]
