# Generated by Django 3.0.14 on 2024-02-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_mentor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='emp_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
