# Generated by Django 3.0.14 on 2024-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20240223_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
