# Generated by Django 3.0.14 on 2024-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_mentor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
