# Generated by Django 3.0.14 on 2024-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_auto_20240224_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
