# Generated by Django 3.0.14 on 2024-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_auto_20240227_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
