# Generated by Django 5.0.3 on 2024-03-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0008_auto_20240228_1048'),
        ('mentor', '0008_auto_20240229_1220'),
    ]

    operations = [
    ]
