# Generated by Django 3.0.14 on 2024-03-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_examiner_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='skill',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
