# Generated by Django 3.0.14 on 2024-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20240313_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='mentor_image',
            field=models.ImageField(default=8, upload_to='static/Faculty/'),
            preserve_default=False,
        ),
    ]
