# Generated by Django 3.0.14 on 2024-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20240207_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_designation',
            field=models.CharField(default='Assistant professor', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_image',
            field=models.ImageField(default='', upload_to='static/Faculty/'),
            preserve_default=False,
        ),
    ]
