# Generated by Django 3.0.14 on 2024-02-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20240207_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='sub_domain',
        ),
        migrations.AddField(
            model_name='skill',
            name='sector',
            field=models.CharField(default='IT', max_length=30),
            preserve_default=False,
        ),
    ]
