# Generated by Django 3.0.14 on 2024-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20240207_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_account',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
