# Generated by Django 3.0.14 on 2024-02-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20240208_1151'),
        ('management', '0007_auto_20240209_1555'),
    ]

    operations = [
    ]
