# Generated by Django 5.0.2 on 2024-02-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_result_student'),
        ('student', '0008_auto_20240220_1428'),
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_type', models.CharField(blank=True, max_length=50, null=True)),
                ('project_score', models.IntegerField(blank=True, null=True)),
                ('certification_status', models.BooleanField(default=False)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('skill_status', models.CharField(default='pending', max_length=20)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
