# Generated by Django 5.0.2 on 2024-02-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_students_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_skills',
            name='domain',
            field=models.CharField(default='IT', max_length=20),
        ),
        migrations.AddField(
            model_name='students_skills',
            name='sector',
            field=models.CharField(default='web development', max_length=20),
        ),
    ]
