# Generated by Django 5.0.2 on 2024-02-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_students_skills_domain_students_skills_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_skills',
            name='branch',
            field=models.CharField(default='CSE', max_length=6),
        ),
    ]
