# Generated by Django 5.0.2 on 2024-02-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_students_skills_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students_skills',
            name='domain',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students_skills',
            name='sector',
            field=models.CharField(max_length=20),
        ),
    ]
