# Generated by Django 5.0.2 on 2024-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_skill_parameters_alter_students_skills_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_skills',
            name='level',
            field=models.CharField(default='beginner', max_length=15),
        ),
    ]
