# Generated by Django 3.0.14 on 2024-02-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_students_skills_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students_skills',
        ),
    ]
