# Generated by Django 3.0.14 on 2024-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_delete_students_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
