# Generated by Django 3.0.14 on 2024-03-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_skill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='parameters',
        ),
    ]
