# Generated by Django 3.0.14 on 2024-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
