# Generated by Django 3.0.14 on 2024-02-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20240208_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
