# Generated by Django 3.0.14 on 2024-02-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20240212_1249'),
        ('quiz', '0009_auto_20240212_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_skills',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
    ]
