# Generated by Django 3.0.14 on 2024-02-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20240214_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_skill_exam_applications',
            old_name='applied_date',
            new_name='completed_date',
        ),
        migrations.RenameField(
            model_name='student_skill_exam_applications',
            old_name='granted_date',
            new_name='requested_date',
        ),
        migrations.AddField(
            model_name='student_skill_exam_applications',
            name='marks_obtained',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student_skill_exam_applications',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
