# Generated by Django 3.0.14 on 2024-02-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20240220_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_skills',
            name='assessed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
