# Generated by Django 3.0.14 on 2024-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20240220_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_criteria',
            fields=[
                ('skill_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=15)),
                ('parameters', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
