# Generated by Django 3.0.14 on 2024-02-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20240213_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='skill',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
