# Generated by Django 3.0.14 on 2024-02-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20240212_1249'),
        ('quiz', '0011_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_skills',
            name='skill_status',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.CreateModel(
            name='student_skill_exam_applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('mentor_identity_number', models.CharField(max_length=30)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('granted_date', models.DateField(blank=True, null=True)),
                ('application_status', models.CharField(max_length=30)),
                ('skill_name', models.CharField(max_length=30)),
                ('assessed_by', models.CharField(max_length=30)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
        ),
    ]
