# Generated by Django 3.0.14 on 2024-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20240213_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_skill_exam_applications',
            name='exam_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_skill_exam_applications',
            name='application_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
