# Generated by Django 3.0.14 on 2024-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20240215_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_skill_exam_applications',
            name='marks_obtained',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_skill_exam_applications',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students_skills',
            name='assessed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
