# Generated by Django 3.0.14 on 2024-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_achievements_achieve_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='achieve_file',
            field=models.FileField(blank=True, null=True, upload_to='students_files/'),
        ),
    ]
