# Generated by Django 3.0.14 on 2024-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_mentorchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorchangelog',
            name='emp_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mentorchangelog',
            name='men_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
