# Generated by Django 3.0.14 on 2024-02-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentor'),
        ('student', '0003_student_td'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='TD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='mentor.mentor'),
        ),
    ]
