# Generated by Django 3.0.14 on 2024-04-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20240415_1236'),
        ('student', '0003_auto_20240410_1048'),
    ]

    operations = [
    ]
