# Generated by Django 3.0.14 on 2024-02-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
        ('student', '0004_achievements_attendance_backlogs_certifications_competitive_exam_education_details_extra_curriculars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='TD',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
