# Generated by Django 3.0.14 on 2024-02-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_delete_students_skills'),
        ('teacher', '0002_teacher_salary'),
        ('student', '0008_auto_20240220_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='CSE', max_length=6)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_type', models.CharField(blank=True, max_length=50, null=True)),
                ('project_score', models.IntegerField(blank=True, null=True)),
                ('certification_status', models.BooleanField(default=False)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('skill_status', models.CharField(default='pending', max_length=20)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher')),
                ('skill_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Skill')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
