# Generated by Django 3.0.14 on 2024-02-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20240223_1040'),
        ('student', '0008_auto_20240220_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor'),
        ),
    ]
