# Generated by Django 3.0.14 on 2024-02-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20240226_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_skills',
            name='branch',
        ),
    ]
