# Generated by Django 3.0.14 on 2024-02-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_department'),
        ('student', '0010_remove_students_skills_branch'),
    ]

    operations = [
    ]
