# Generated by Django 3.0.14 on 2024-02-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_merge_20240229_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
