# Generated by Django 3.0.14 on 2024-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_delete_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_score',
            field=models.IntegerField(default=0),
        ),
    ]
