# Generated by Django 3.0.14 on 2024-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_skills',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
