# Generated by Django 3.0.14 on 2024-04-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='skill',
        ),
    ]
