# Generated by Django 3.0.14 on 2024-02-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentor'),
        ('student', '0004_auto_20240210_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='TD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='mentor.mentor'),
        ),
    ]
